apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql56-primary
  labels:
    app: dev
spec:
  selector:
    matchLabels:
      app: dev
      tier: db-primary
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dev
        tier: db-primary
    spec:
      containers:
        - name: mysql56-primary
          image: rnidev/mysql56-barracuda
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql56-primary-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql56-primary-configs
              mountPath: /etc/mysql/conf.d/mysql56-primary.cnf
              subPath: mysql56-primary.cnf
      volumes:
      - name: mysql56-primary-persistent-storage
        persistentVolumeClaim:
          claimName: mysql56-primary-pvc
      - name: mysql56-primary-configs
        configMap:
          name: mysql56-primary-conf.d
---
