apiVersion: v1
kind: Service
metadata:
  name: mysql56-replica-svc
  labels:
    app: dev
spec:
  ports:
    - port: 3357
      targetPort: 3306
      protocol: TCP
  selector:
    app: dev
    tier: db-replica
  type: LoadBalancer
