apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql56-replica-pv
  labels:
    type: local
spec:
  storageClassName: mysql56-replica-volume
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/nakamura/var/k8-local/mysql56-replica"
