apiVersion: v1
kind: Service
metadata:
  name: memcached-svc
  labels:
    app: dev
spec:
  ports:
    - port: 11211
      targetPort: 11211
  selector:
    app: dev
    tier: memcached
  type: LoadBalancer
