apiVersion: v1
kind: Service
metadata:
  name: mysql56-master-svc
  labels:
    app: dev
spec:
  ports:
    - port: 3306
      nodePort: 30066
      protocol: TCP
  selector:
    app: dev
    tier: db
  type: NodePort
