apiVersion: v1
kind: Service
metadata:
  name: mysql56-master-svc
  labels:
    app: dev
spec:
  ports:
    - port: 3356
      targetPort: 3306
      protocol: TCP
  selector:
    app: dev
    tier: db-master
  type: LoadBalancer
