apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: dev
spec:
  selector:
    matchLabels:
      app: dev
      tier: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dev
        tier: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-volume
              mountPath: /data
      volumes:
      - name: redis-volume
        persistentVolumeClaim:
          claimName: redis-pvc
---
