apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: dev
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: dev
    tier: redis
  type: LoadBalancer
